### ISSUE TITLE
NullPointerException with DEBUG logger level

### ISSUE THREAD

**Issue by alphatan** [Netflix/feign#255] opened 2015-08-06 10:03 UTC
Repro:

    1. init feign with:
        Feign.builder()
            .logger(new Slf4jLogger())
            .logLevel(feign.Logger.Level.FULL)

    2. set the level of Slf4jLogger to DEBUG

    3. call a method without response (204, No Content), then
    we would see the exception.

StackTrace:

    java.lang.NullPointerException: in
        at feign.Util.checkNotNull(Util.java:99)
        at feign.Util.toByteArray(Util.java:212)
        at feign.Logger.logAndRebufferResponse(Logger.java:94)
        at feign.slf4j.Slf4jLogger.logAndRebufferResponse(Slf4jLogger.java:62)
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:103)
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:71)
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:94)
        at com.sun.proxy.$Proxy27.deleteCredential(Unknown Source)
        at ...

Problem positioning:

    feign.Logger#logAndRebufferResponse(), line 94
    
        byte[] bodyData = Util.toByteArray(response.body().asInputStream());

    The call response.body().asInputStream() returns null.

Affected versions: 

    8.5.0, 8.6.0 (only these two versions were tested.)

**Comment by adriancole** [comment] 2015-08-06 14:03
Thanks for reporting, especially this is easy to understand!

This should be a dupe, fixed in 8.7.0. Can you please verify?

**Comment by alphatan** [comment] 2015-08-06 14:49
@adriancole, the problem also happens in 8.7.0 .

**Comment by adriancole** [comment] 2015-08-06 14:51
Sad face... OK! Will take a look today. Thanks for testing.

**Comment by adriancole** [comment] 2015-08-06 15:17
Strange that `response.body().asInputStream()` is returning null. It isn't documented as being ok to return null. It seems apache has a bug where it can return null on .asInputStream(). Are you using the apache client, or something else?

**Comment by adriancole** [comment] 2015-08-06 15:35
Looks like there was also a bug in RibbonClient.

**Comment by adriancole** [comment] 2015-08-06 15:41
oops.. no bug in RibbonClient. deleting..

**Comment by adriancole** [comment] 2015-08-06 15:46
@alphatan I could only reproduce this bug with apache.. hope that's what you were using! see #256

**Closed** 2015-08-06 17:19 UTC

**Comment by adriancole** [comment] 2015-08-06 17:23
ok 8.7.1 is on the way. I could only reproduce this with apache http client. Hopefully, that was your use case.

**Comment by alphatan** [comment] 2015-08-06 23:22
@adriancole Yes, I'm using the apache http client. And  thanks for your quick fix.

**Comment by adriancole** [comment] 2015-08-06 23:29
whew! well glad this was the fix!
