### ISSUE TITLE
Headers replacement only works when replacement is at the beginning of the value

### ISSUE THREAD

**Issue by ahus1** [Netflix/feign#325] opened 2016-02-09 17:12 UTC
Working with replacements in headers I found that they only work if there is a replacement at the beginning of the value due to RequestTemplate.java:219

        if (value.indexOf('{') == 0) {
          resolved = expand(value, unencoded);
        }

Works: 

    @Headers("Cache-Control: {cachecontrol}")

Doesn't work:

    @Headers("Cache-Control: max-age={age}")

I wonder if this is intended. If it is intended, I would recommend to update the JavaDoc. If not, the implementation should be updated. 

I'm happy to provide a pull request once I know which way to go.

**Comment by adriancole** [comment] 2016-02-10 00:56
This is a dupe of #288 Feel free to raise a PR (and thanks for offering!)

**Closed** 2016-02-10 00:56 UTC

**Comment by ahus1** [comment] 2016-02-10 09:03
#288 ready as if you are willing to accept more liberal replacements in headers. PR #326 is on the way.
