### ISSUE TITLE
how can use feign client fallback in implemention

### ISSUE THREAD

**Issue by Dreampie** [Netflix/feign#319] opened 2016-01-16 05:09 UTC
like this:
```java
@FeignClient(value="userService")
public interface UserService {
  @RequestMapping(value = UserConstants.USERS_ID_PATH, method = RequestMethod.GET)
  ResponseEntity<UserEntity> findById(@PathVariable("id") int id);

  @RequestMapping(value = UserConstants.USERS_PATH, method = RequestMethod.POST, consumes = MediaType.APPLICATION_JSON_VALUE)
  ResponseEntity<UserEntity> save(@RequestBody UserEntity user);
}



public interface UserServiceImpl impletment UserService{

  @Fallback("fallbackFindById")
  ResponseEntity<UserEntity> findById(@PathVariable("id") int id){
  }

  ResponseEntity<UserEntity> fallbackFindById(int id){
  }

  //not need fallback
  public ResponseEntity<UserEntity> save(@RequestBody UserEntity user) {
  }
}
```

**Comment by spencergibb** [comment] 2016-02-11 15:09
@adriancole this should be close as this is a duplicate of #317 here and the question is about spring-cloud-netflix.

**Closed** 2016-02-11 15:10 UTC
